#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function apt_install
{
    PACKAGE=$1
    ARCH=$2
    VERSION=$3

    if ! [ "$VERSION" == "" ];
    then
        VERSION="=${VERSION}~${DISTRO_VERSION_NAME}-1"
    fi

    if ! [ "$ARCH" == "" ];
    then
        ARCH=":${ARCH}"
    fi

    echo ""
    echo "Installing ${PACKAGE}${ARCH}${VERSION} ..."
    echo "-------------------------------------------"

    sudo apt install -y ${PACKAGE}${ARCH}${VERSION}

    if ! [ "$?" == "0" ];
    then
        abort "Package '${PACKAGE}${ARCH}${VERSION} failed to install."
    fi
}


function usage
{
    echo "Usage: apt_install_wine32 [branch] [version]"
    echo ""
    echo "Branch is one of these: stable, devel or staging."
    echo ""
    echo "If no branch or version is given, staging is used and"
    echo "the last available version will be installed."
    echo ""
}


if [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


SCRIPT_DIR=$(realpath $(dirname $0))




WINE_BRANCH=$1
WINE_VERSION=$2

export DISTRO_VERSION_NAME=$("$SCRIPT_DIR/os_version_name")


if [ "$WINE_BRANCH" == "" ];
then
    WINE_BRANCH="staging"
fi


source "$SCRIPT_DIR/check_site"

if ! [ "$WINE_URL_OK" == "1" ];
then
    abort "Can't download Wine."
fi


if ! [ "$WINE_BRANCH" == "stable" ] && ! [ "$WINE_BRANCH" == "devel" ] && \
   ! [ "$WINE_BRANCH" == "staging" ];
then
    abort "Wrong branch name: '$WINE_BRANCH'."
fi


"$SCRIPT_DIR/prepare_apt"


if ! [ "$?" == "0" ];
then
    abort "APT failed preparing."
fi


echo "-----------------------------"
echo "Installing Wine (32 bits) ..."
echo "-----------------------------"

sudo dpkg --add-architecture i386
echo "Added i386 architecture to dpkg if wasn't available yet."
echo ""


echo ""
echo "Updating available packages ..."
echo "-------------------------------"

sudo apt update


if [ "$WINE_VERSION" == "" ];
then
    apt_install wine-${WINE_BRANCH} i386
    apt_install wine-${WINE_BRANCH}-i386 i386
else
    apt_install wine-${WINE_BRANCH} i386 ${WINE_VERSION}
    apt_install wine-${WINE_BRANCH} i386 ${WINE_VERSION}
fi


if ! [ -f "/usr/bin/winetricks" ];
then
    "$SCRIPTS_DIR/apt_install_winetricks"
fi


echo ""
echo "Done."












