#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


SCRIPT_DIR=$(realpath $(dirname $0))



echo ""
echo "Checking for Winetricks ..."


if [ -f "/usr/bin/winetricks" ];
then
    abort "Winetricks is already installed."
fi


echo ""
echo "Not found. Installing ..."
echo "-------------------------"


FOUND_PACKAGES=$(sudo apt-cache search --names-only winetricks)

if [ "$FOUND_PACKAGES" == "" ];
then
    "$SCRIPT_DIR/prepare_apt"

    # TMP_CONTRIB_SOURCES_LIST="/var/tmp/debian-contrib.sources"
    # CONTRIB_SOURCES_LIST="/etc/apt/sources.list.d/debian-contrib.sources"

    # echo "Types: deb" > $TMP_CONTRIB_SOURCES_LIST
    # echo "URIs: http://deb.debian.org/debian" >> $TMP_CONTRIB_SOURCES_LIST
    # echo "Suites: bookworm bookworm-updates" >> $TMP_CONTRIB_SOURCES_LIST
    # echo "Components: contrib" >> $TMP_CONTRIB_SOURCES_LIST
    
    # echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" \
    #         >> $TMP_CONTRIB_SOURCES_LIST

    # sudo mv "${TMP_CONTRIB_SOURCES_LIST}" "${CONTRIB_SOURCES_LIST}"

    # if ! [ "$?" == "0" ];
    # then
    #     abort "Failed enabling 'contrib' packages."
    # fi

    # echo "Enabled 'contrib' packages."

    # echo ""
    # echo "Refreshing APT database ..."
    # echo "---------------------------"

    # sudo apt update 
fi


echo ""
echo "Installing Winetricks ..."
echo "-------------------------"

sudo apt install -y winetricks


if [ "$?" == "0" ];
then
    echo ""
    echo "Done."
    echo ""
fi





