#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}




echo -n "Checking if Wine site is available... "
curl -s https://dl.winehq.org > /dev/null

if [ "$?" == "0" ];
then
    WINE_URL_OK=1
    echo "OK"
    echo ""
else
    echo "ERROR"
    echo ""
fi


if ! [ "$WINE_URL_OK" == "1" ];
then
    abort "Can't download Wine."
fi
