#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: exec_type <executable path>"
    echo ""
    echo "Will output linux/windows-i386/amd64, depending of the"
    echo "executable architecture, or unknown if none of these."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




EXEC=$1
FILE_TYPE=$(file -L "$EXEC")


echo ${FILE_TYPE} | grep "ELF 32-bit" > /dev/null

if [ "$?" == "0" ];
then
    echo "linux-i386"
    echo ""
else
    echo ${FILE_TYPE} | grep "ELF 64-bit" > /dev/null

    if [ "$?" == "0" ];
    then
        echo "linux-amd64"
        echo ""
    else
        echo ${FILE_TYPE} | grep "PE32 executable" > /dev/null

        if [ "$?" == "0" ];
        then
            echo "windows-i386"
            echo ""
        else
            echo ${FILE_TYPE} | grep "PE32+ executable" > /dev/null

            if [ "$?" == "0" ];
            then
                echo "windows-amd64"
                echo ""
            fi
        fi
    fi
fi


