#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Shows the URLs for downloading Wine source.list and GPG key."
    echo ""
    echo "Usage: get_wine_urls [-q|--quiet]"
    echo ""
    echo "-q|--quiet: No URL will be printed."
    echo ""    
    echo "Sets two variables: WINE_SOURCES_URL and WINE_GPG_URL."
    echo "These will be accesible if the script is called with . or 'source'."
    echo ""
}


if [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


SCRIPT_DIR=$(realpath $(dirname $0))


if [ "$3" == "-q" ] || [ "$3" == "--quiet" ];
then
    QUIET=1
fi


DISTRO_NAME=$("$SCRIPT_DIR/os_name")
DISTRO_VERSION_NAME=$("$SCRIPT_DIR/os_version_name")


WINE_BUILDS_URL="https://dl.winehq.org/wine-builds"

DISTRO_BUILDS_URL="${WINE_BUILDS_URL}/${DISTRO_NAME}"
DISTRO_BUILDS_URL+="/dists/${DISTRO_VERSION_NAME}"

WINE_SOURCES_URL="${DISTRO_BUILDS_URL}/"
WINE_SOURCES_URL+="winehq-${DISTRO_VERSION_NAME}.sources"

WINE_GPG_URL="${WINE_BUILDS_URL}/winehq.key"


if ! [ "$QUIET" == "1" ];
then
    echo "${WINE_SOURCES_URL} ${WINE_GPG_URL}"
fi





