#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: get_wine_urls <branch> <version> [-q|--quiet]"
    echo ""
    echo "Branch is one of these: stable, devel or staging."
    echo ""
    echo "Shows the URLs of Wine sources.list and the GPG key."
    echo "Also exports two variables: WINE_SOURCES_URL and WINE_GPG_URL"
    echo "If -q|--quiet is specified, no URL will be printed."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


SCRIPT_DIR=$(realpath $(dirname $0))




WINE_BRANCH=$1
WINE_VERSION=$2

if [ "$3" == "-q" ] || [ "$3" == "--quiet" ];
then
    QUIET=1
fi


if ! [ "$WINE_BRANCH" == "stable" ] && ! [ "$WINE_BRANCH" == "devel" ] && \
   ! [ "$WINE_BRANCH" == "staging" ];
then
    abort "Wrong branch name: '$WINE_BRANCH'."
fi


DISTRO_NAME=$("$SCRIPT_DIR/os_name")
DISTRO_VERSION_NAME=$("$SCRIPT_DIR/os_version_name")


WINE_BUILDS_URL="https://dl.winehq.org/wine-builds"

DISTRO_BUILDS_URL="${WINE_BUILDS_URL}/${DISTRO_NAME}"
DISTRO_BUILDS_URL+="/dists/${DISTRO_VERSION_NAME}"

WINE_SOURCES_URL="${DISTRO_BUILDS_URL}/"
WINE_SOURCES_URL+="winehq-${DISTRO_VERSION_NAME}.sources"

WINE_GPG_URL="${WINE_BUILDS_URL}/winehq.key"


if ! [ "$QUIET" == "1" ];
then
    echo "${WINE_SOURCES_URL} ${WINE_GPG_URL}"
fi





