#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: get_wine_urls <branch> <version>"
    echo ""
    echo "Branch is one of these: stable, devel or staging."
    echo "Exports two variables: WINE_SOURCES_URL and WINE_GPG_URL"
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


SCRIPT_DIR=$(realpath $(dirname $0))




WINE_BRANCH=$1
WINE_VERSION=$2


if ! [ "$WINE_BRANCH" == "stable" ] && ! [ "$WINE_BRANCH" == "devel" ] && \
   ! [ "$WINE_BRANCH" == "staging" ];
then
    abort "Wrong branch name: '$WINE_BRANCH'."
fi


source "$SCRIPT_DIR/os_name" --quiet


WINE_BUILDS_URL="https://dl.winehq.org/wine-builds"

DISTRO_BUILDS_URL="${WINE_BUILDS_URL}/${DISTRO_NAME}"
DISTRO_BUILDS_URL+="/dists/${DISTRO_VERSION_NAME}"

export WINE_SOURCES_URL="${DISTRO_BUILDS_URL}/"
export WINE_SOURCES_URL+="winehq-${DISTRO_VERSION_NAME}.sources"

export WINE_GPG_URL="${WINE_BUILDS_URL}/winehq.key"








