#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: install_unpacked_wine <Wine path>"
    echo ""
}


SCRIPT_DIR=$(realpath $(dirname $0))




WINE_PATH=$1


FIND_RESULT=$(find "${WINE_PATH}/opt" -type f -name "wineboot")

if [ "$FIND_RESULT" == "" ];
then
    abort "No Wine installation found at '${WINE_PATH}'."
fi


echo "Installing Wine..."
echo "------------------"



cp -r "$WINE_PATH/opt/wine"









