#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


if ! [ "$TERMUX_VERSION" == "" ];
then
    abort "This script isn't for Termux."
fi


sudo -v

if ! [ "$?" == "0" ];
then
    abort "You need to be root, or have sudo permissions."
fi




echo ""
echo "Installing dependencies for wine (64 bits)..."
echo "---------------------------------------------"

WINE64_DEPS="libasound2:arm64 libc6:arm64 libglib2.0-0:arm64"
WINE64_DEPS+=" libgphoto2-6:arm64 libgphoto2-port12:arm64"
WINE64_DEPS+=" libgstreamer-plugins-base1.0-0:arm64 libgstreamer1.0-0:arm64"
WINE64_DEPS+=" libldap-2.4-2:arm64 libopenal1:arm64 libpcap0.8:arm64"
WINE64_DEPS+=" libpulse0:arm64 libsane1:arm64 libudev1:arm64"
WINE64_DEPS+=" libusb-1.0-0:arm64 libvkd3d1:arm64 libx11-6:arm64"
WINE64_DEPS+=" libxext6:arm64 libasound2-plugins:arm64"
WINE64_DEPS+=" ocl-icd-libopencl1:arm64 libncurses6:arm64 libncurses5:arm64"
WINE64_DEPS+=" libcap2-bin:arm64 libcups2:arm64 libdbus-1-3:arm64"
WINE64_DEPS+=" libfontconfig1:arm64 libfreetype6:arm64 libglu1-mesa:arm64"
WINE64_DEPS+=" libglu1:arm64 libgnutls30:arm64 libgssapi-krb5-2:arm64"
WINE64_DEPS+=" libkrb5-3:arm64 libodbc1:arm64 libosmesa6:arm64"
WINE64_DEPS+=" libsdl2-2.0-0:arm64 libv4l-0:arm64 libxcomposite1:arm64"
WINE64_DEPS+=" libxcursor1:arm64 libxfixes3:arm64 libxi6:arm64"
WINE64_DEPS+=" libxinerama1:arm64 libxrandr2:arm64 libxrender1:arm64"
WINE64_DEPS+=" libxxf86vm1:arm64"

sudo apt install -y $WINE64_DEPS

exit $?
