#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: install_unpacked_wine <Wine path>"
    echo ""
}


SCRIPT_DIR=$(realpath $(dirname $0))


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




WINE_PATH=$1


FIND_RESULT=$(find "${WINE_PATH}/opt" -type f -name "wineboot")

if [ "$FIND_RESULT" == "" ];
then
    abort "No Wine installation found at '${WINE_PATH}'."
fi


WINE_OPT="${WINEPATH}/opt"
WINE_USR="${WINEPATH}/usr"

WINE_FOLDER_REGEX=".*/wine-\(stable\|staging\|devel\)$"
WINE_PATH=$(find "${WINE_OPT}" -type d -regex "${WINE_FOLDER_REGEX}")
WINE_DIRNAME=$(basename "$WINE_PATH")


echo "Installing Wine..."
echo "------------------"

cp -r $WINE_OPT /opt/

cp -r $WINE_USR/share/doc/wine-staging /usr/share/doc/
cp $WINE_USR/share/doc/wine-staging-* /usr/share/doc/
cp $WINE_USR/share/lintian/overrides/* /usr/share/lintian/overrides/

ln -s /opt/$WINE_DIRNAME/bin/wine /usr/local/bin/wine
ln -s /opt/$WINE_DIRNAME/bin/wine64 /usr/local/bin/wine64
ln -s /opt/$WINE_DIRNAME/bin/winecfg /usr/local/bin/winecfg
ln -s /opt/$WINE_DIRNAME/bin/wineboot /usr/local/bin/wineboot


echo "Done."
echo ""







