#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}




SCRIPT_DIR=$(realpath $(dirname $0))


source "$SCRIPT_DIR/check_site"

if [ "$WINE_URL_OK" == "1" ];
then
    source "$SCRIPT_DIR/prepare_apt"

    if ! [ "$?" == "0" ];
    then
        abort "Could not prepare APT database"
    fi


    source "$SCRIPT_DIR/packages_arch"

    if [[ $PACKAGES_ARCH == arm* ]];
    then
        echo "We are in ARM. Wine will be manually installed instead of"
        echo "calling 'apt install'."
        echo ""
    fi
fi


