#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}




if ! [ "$TERMUX_VERSION" == "" ];
then
    abort "This script isn't for Termux."
fi


sudo echo ""

if ! [ "$?" == "0" ];
then
    abort "You need to be root, or have sudo permissions."
fi


ARCH=$(uname -m)

if ! [[ $ARCH == armv* ]] && ! [ "$ARCH" == "aarch64" ];
then
    abort "You need a ARMv7 or ARM64 device for running this script."
fi


if ! [ -f "$HOME/.wine32_deps_installed" ];
then
    echo ""
    echo "Installing dependencies for Wine (32 bits) in ARM ..."
    echo "-----------------------------------------------------"

    WINE_DEPS="libasound2:armhf libc6:armhf libglib2.0-0:armhf"
    WINE_DEPS+=" libgphoto2-6:armhf libgphoto2-port12:armhf"
    WINE_DEPS+=" libgstreamer-plugins-base1.0-0:armhf libgstreamer1.0-0:armhf"
    WINE_DEPS+=" libldap-2.4-2:armhf libopenal1:armhf libpcap0.8:armhf"
    WINE_DEPS+=" libpulse0:armhf libsane1:armhf libudev1:armhf"
    WINE_DEPS+=" libusb-1.0-0:armhf libvkd3d1:armhf libx11-6:armhf"
    WINE_DEPS+=" libxext6:armhf libasound2-plugins:armhf"
    WINE_DEPS+=" ocl-icd-libopencl1:armhf libncurses6:armhf libncurses5:armhf"
    WINE_DEPS+=" libcap2-bin:armhf libcups2:armhf libdbus-1-3:armhf"
    WINE_DEPS+=" libfontconfig1:armhf libfreetype6:armhf libglu1-mesa:armhf"
    WINE_DEPS+=" libglu1:armhf libgnutls30:armhf libgssapi-krb5-2:armhf"
    WINE_DEPS+=" libkrb5-3:armhf libodbc1:armhf libosmesa6:armhf"
    WINE_DEPS+=" libsdl2-2.0-0:armhf libv4l-0:armhf libxcomposite1:armhf"
    WINE_DEPS+=" libxcursor1:armhf libxfixes3:armhf libxi6:armhf"
    WINE_DEPS+=" libxinerama1:armhf libxrandr2:armhf libxrender1:armhf"
    WINE_DEPS+=" libxxf86vm1:armhf"

    sudo apt install -y $WINE_DEPS

    RESULT=$?

    if [ "$?" == "0" ];
    then
        touch "$HOME/.wine32_deps_installed"
    fi

    exit $RESULT
fi
