#!/bin/bash


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}




if ! [ "$TERMUX_VERSION" == "" ];
then
    abort "This script isn't for Termux."
fi


sudo echo ""

if ! [ "$?" == "0" ];
then
    abort "You need to be root, or have sudo permissions."
fi


if ! [ "$(uname -m)" == "x86_64" ];
then
    abort "You need a x86 (64 bits) device to run this script."
fi


if ! [ -f "/usr/lib/x86_64-linux-gnu/libvkd3d.so.1" ];
then
    echo ""
    echo "Installing dependencies for Wine (64 bits) ..."
    echo "----------------------------------------------"

    WINE_DEPS="libasound2 libavcodec58 libavformat58 "
    WINE_DEPS+="libavutil56 libc6 libglib2.0-0 libgphoto2-6 "
    WINE_DEPS+="libgphoto2-port12 libgstreamer-plugins-base1.0-0 "
    WINE_DEPS+="libgstreamer1.0-0 libpcap0.8 libpcsclite1 "
    WINE_DEPS+="libpulse0 libsane1 libudev1 libunwind8 libusb-1.0-0 "
    WINE_DEPS+="libwayland-client0 libwayland-egl1 libx11-6 "
    WINE_DEPS+="libxext6 libxkbcommon0 libxkbregistry0 "
    WINE_DEPS+="ocl-icd-libopencl1 libasound2-plugins libncurses6 "
    WINE_DEPS+="libcairo2 libcap2-bin libcups2 "
    WINE_DEPS+="libdbus-1-3 libfontconfig1 libfreetype6 "
    WINE_DEPS+="libglu1-mesa libgnutls30 libgssapi-krb5-2 "
    WINE_DEPS+="libgtk-3-0 libkrb5-3 libodbc2 "
    WINE_DEPS+="libosmesa6 libsdl2-2.0-0 libv4l-0 libva-drm2 "
    WINE_DEPS+="libva-x11-2 libva2 libxcomposite1 libxcursor1 "
    WINE_DEPS+="libxfixes3 libxi6 libxinerama1 libxrandr2 "
    WINE_DEPS+="libxrender1 libxxf86vm1 libvulkan1"

    sudo apt install -y $WINE_DEPS

    exit $?
fi
