#!/bin/bash

MACHINE_ARCH=$(uname -m)


if [[ $MACHINE_ARCH == arm* ]];
then
    echo "armhf"

elif [ "$MACHINE_ARCH" == "aarch64" ];
then
    echo "arm64"

elif [ "$MACHINE_ARCH" == "x86_64" ];
then
    echo "amd64"

elif [[ $MACHINE_ARCH == x86* ]];
then
    echo "i386"
else
    echo "$MACHINE_ARCH"
fi

echo ""


















