#!/bin/bash


if [ "$1" == "-q" ] || [ "$1" == "--quiet" ];
then
    QUIET=1
fi


MACHINE_ARCH=$(uname -m)


if [[ $MACHINE_ARCH == arm* ]];
then
    PACKAGES_ARCH="armhf"

elif [ "$MACHINE_ARCH" == "aarch64" ];
then
    PACKAGES_ARCH="arm64"

elif [ "$MACHINE_ARCH" == "x86_64" ];
then
    PACKAGES_ARCH="amd64"

elif [[ $MACHINE_ARCH == x86* ]];
then
    PACKAGES_ARCH="i386"
else
    echo "$MACHINE_ARCH"
fi


echo "$PACKAGES_ARCH"
echo ""


















