#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""

    exit 1
}


function enable_debian_contrib
{
    TMP_SOURCES_LIST="/var/tmp/debian-contrib.sources"
    SOURCES_LIST="/etc/apt/sources.list.d/debian-contrib.sources"

    DEB_VERSION=$DISTRO_VERSION_NAME

    echo "Types: deb" > $TMP_SOURCES_LIST
    echo "URIs: http://deb.debian.org/debian" >> $TMP_SOURCES_LIST
    echo "Suites: ${DEB_VERSION} ${DEB_VERSION}-updates" >> $TMP_SOURCES_LIST
    echo "Components: contrib" >> $TMP_SOURCES_LIST

    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" \
            >> $TMP_SOURCES_LIST

    sudo mv "${TMP_SOURCES_LIST}" "${SOURCES_LIST}"

    if ! [ "$?" == "0" ];
    then
        abort "Failed enabling 'contrib' packages."
    fi

    sudo apt update

    echo ""
    echo "Enabled 'contrib' packages."
    echo ""
}


SCRIPT_DIR=$(realpath $(dirname $0))




export PATH=$PATH:$SCRIPT_DIR:$SCRIPT_DIR/aux


echo "Checking if APT is ready for downloading Wine and Winetricks..."
echo ""


export DISTRO_NAME=$(os_name)
export DISTRO_VERSION_NAME=$(os_version_name)


source "$SCRIPT_DIR/aux/get_wine_urls"


if ! [ -f "/etc/apt/keyrings/winehq-archive.key" ];
then
    if [ "$WINE_GPG_URL" == "" ];
    then
        abort "Could not obtain Wine GPG download URL."
    fi

    if ! [ -d "/etc/apt/keyrings" ];
    then
        sudo mkdir "/etc/apt/keyrings"
    fi

    sudo wget -O /etc/apt/keyrings/winehq-archive.key $WINE_GPG_URL

    if ! [ "$?" == "0" ];
    then
        abort "Failed downloading Wine GPG key."
    fi

    echo "Added Wine GPG key to keyrings."
    echo ""

else
    echo "Wine GPG key already present."
    echo ""
fi


if [ "$WINE_SOURCES_URL" == "" ];
then
    abort "Could not obtain Wine sources.list for APT."
fi


echo ""
echo "Checking for updated APT sources.list..."
echo "----------------------------------------"

SOURCES_LIST_FILE="/etc/apt/sources.list.d/"
SOURCES_LIST_FILE+="winehq-${DISTRO_VERSION_NAME}.sources"

sudo wget -NP /etc/apt/sources.list.d/ $WINE_SOURCES_URL

if [ "$?" == "0" ];
then
    echo "Updated sources.list in APT database."
    echo ""
else
    if [ "$?" == "1" ] && [ -f "${SOURCES_LIST_FILE}" ];
    then
        echo "Sources.list is up to date."
        echo ""
    fi
fi


if [ "$DISTRO_NAME" == "debian" ];
then
    if [ -f "/etc/apt/sources.list" ];
    then
        cat /etc/apt/sources.list | grep contrib > /dev/null
        CONTRIB_ENABLED=$?

    elif [ -f "/etc/apt/sources.list.d/debian.sources" ];
    then
        cat /etc/apt/sources.list.d/debian.sources | grep contrib > /dev/null
        CONTRIB_ENABLED=$?
    fi


    if ! [ "$CONTRIB_ENABLED" == "0" ];
    then
        echo "Didn't found 'contrib' enabled in sources list. Trying to enable..."
        echo ""

        enable_debian_contrib
    fi
fi


echo "All seems ready for APT downloading."
echo ""


