#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: switch-wine <Wine path>"
    echo "Update the /usr/local/bin symlinks to use another Wine installation."
    echo ""
}


if ! [ "$TERMUX_VERSION" == "" ];
then
    abort "This script isn't for Termux."
fi


sudo -v

if ! [ "$?" == "0" ];
then
    abort "You need to be root, or have sudo permissions."
fi


if [ "$1" == "" ] || [ "$1" == "" ] || [ "$1" == "" ];
then
    usage
    abort
fi




WINE_PATH=$1


if ! [ -f "${WINE_PATH}/bin/wineboot" ];
then
    abort "Wine not detected '$WINE_PATH'."
fi


sudo ln -sf "${WINE_PATH}/bin/wine" /usr/local/bin/wine

if [ -f "${WINE_PATH}/bin/wine64" ];
then
    sudo ln -sf "${WINE_PATH}/bin/wine64" /usr/local/bin/wine64
fi

sudo ln -sf "${WINE_PATH}/bin/wineboot" /usr/local/bin/wineboot
sudo ln -sf "${WINE_PATH}/bin/winecfg" /usr/local/bin/winecfg


echo "Using now Wine installation at ${WINE_PATH}."
echo ""


