#!/bin/bash

function check_for_valid_wine_installation
{
    WINE_PATH=$1

    if ! [ -d "$WINE_PATH/opt/wine-stable" ] && \
       ! [ -d "$WINE_PATH/opt/wine-staging" ] && \
       ! [ -d "$WINE_PATH/opt/wine-devel" ];
    then
        echo "The specified path '$WINE_PATH' in '$HOME/.default_${WINEARCH}_env'"
        echo "isn't a vaild Wine installation (from WineHQ or Lutris)."

        return 1
    fi

    return 0
}


function usage
{
    echo "Usage: . use_wine <Wine installation path>"
    echo "       source use_wine <Wine installation path>"
    echo ""
    echo "Loads the specified Wine environment in the current shell session."
    echo ""
}


SCRIPT_DIR=$(realpath $(dirname ${BASH_SOURCE[0]}))




if [ "$1" == "" ];
then
    usage
else
    export WINE_PATH=$(realpath $1)
fi


if ! [ "$WINE_PATH" == "" ];
then
    if ! [ -f "$WINE_PATH/.wine_version" ];
    then
        echo "No Wine installation detected at '$WINE_PATH'."
        echo ""

    else
        WINE_ARCH=$(cat $WINE_PATH/.wine_arch)
        WINE_BRANCH=$(cat $WINE_PATH/.wine_branch)
        WINE_VERSION=$(cat $WINE_PATH/.wine_version)

        export WINE_BINARIES=$WINE_PATH/opt/wine-${WINE_BRANCH}/bin


        if [ "$WINE_ARCH" == "i386" ];
        then
            export WINE_UTILS=$WINE_PATH/opt/wine-${WINE_BRANCH}/lib/wine/i386-windows

            export WINELOADER="$WINE_BINARIES/wine"
            export WINEDLLPATH=$WINE_UTILS

            echo "$LD_LIBRARY_PATH" | grep -q "wine/i386-unix"

            if ! [ "$?" == "0" ];
            then
                export LD_LIBRARY_PATH+=":$WINE_PATH/opt/wine-${WINE_BRANCH}/lib/wine/i386-unix"
            fi
        else
            export WINE_UTILS=$WINE_PATH/opt/wine-${WINE_BRANCH}/lib64/wine/x86_64-windows

            export WINELOADER="$WINE_BINARIES/wine64"
            export WINEDLLPATH=$WINE_UTILS

            echo "$LD_LIBRARY_PATH" | grep -q "wine/x86_64-unix"

            if ! [ "$?" == "0" ];
            then
                export LD_LIBRARY_PATH+="$WINE_PATH/opt/wine-${WINE_BRANCH}/lib64/wine/x86_64-unix"
            fi
        fi


        export WINESERVER="$WINE_BINARIES/wineserver"
        
        # Needed by winetricks
        export WINE="$WINELOADER"

        alias wine="$WINELOADER"
        alias winecfg="\"$WINELOADER\" \"$WINE_UTILS/winecfg.exe\""


        echo "Activated Wine $WINE_BRANCH ($WINE_VERSION): $WINE_PATH"
        echo ""

        if [ "$(which win_prepare)" == "" ];
        then
            export PATH=$PATH:$SCRIPT_DIR

            echo "Added temporally '$SCRIPT_DIR' to PATH."
            echo ""
        fi
    fi
fi
