#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: win_start <windows executable path>"
    echo "Activates the needed Wine prefix and runs the executable."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


SCRIPT_DIR=$(realpath $(dirname $0))




EXEC=$1
EXEC_NAME=$(basename $EXEC)
EXEC_PATH=$(dirname $EXEC)

ARGS=${@:2}


if [ "$EXEC_PATH/${EXEC_NAME}_winenv" ];
then
    source "$EXEC_PATH/${EXEC_NAME}_winenv"
else
    EXEC_TYPE=$(exec_type "$EXEC")

    if [ "$EXEC_TYPE" == "windows-i386" ];
    then
        echo "Windows (32 bits) binary detected."

        if [ "$HOME/.default_win32_env" ];
        then
            source "$HOME/.default_win32_env"
        fi        

    elif [ "$EXEC_TYPE" == "windows-amd64" ];
    then
        echo "Windows (64 bits) binary detected."

        if [ "$HOME/.default_win64_env" ];
        then
            source "$HOME/.default_win64_env"
        fi
    fi    
fi


if [ "$WINEPREFIX" == "" ] && [ "$WINEARCH" == "" ] && 
   [ "$WINELOADER" == "" ];
then
    echo "No Wine environment was loaded."
    echo ""
    echo "First, install a Wine version with 'download_wine'."
    echo "This will make it the default one if no one is."
    echo ""
    echo "Then, use 'win_prepare' to create a new Wine Prefix with the"
    echo "desired name and architecture (if nothing is specified,"
    echo "the default ones will be used)."
    echo ""
    echo "You can also activate a prefix on your own."
    abort
fi


echo "Executing '$EXEC' $ARGS with Wine ..."
echo ""


"$WINELOADER" "$EXEC" $ARGS
