#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


function usage
{
    echo "Usage: wincd_load <iso path>"
    echo "Loads the given ISO in the prefix's D drive."
    echo ""

    abort
}




if ! [ "$TERMUX_VERSION" == "" ];
then
    abort "This script isn't for Termux."
fi


if ! [ -f "/usr/bin/fuseiso" ];
then
    echo "Installing fuseiso ..."
    echo "----------------------"

    sudo apt install -y fuseiso
fi

if ! [ "$?" == "0" ];
then
    abort "Failed."
fi


if [ "$WIN_D" == "" ];
then
    echo "No WINE prefix loaded."
    echo "Call win_load <prefix name> [win32|win64]"
    echo "Set WIN_ROOT if need to use a different path as prefixes root."
    echo ""

    abort
fi


if ! [ -d "$WIN_D" ];
then
    mkdir -p "$WINEPREFIX/drive_d"
    ln -s "$WINEPREFIX/drive_d" "$WINEPREFIX/dosdevices/d:"
fi


ISO=$1

if ! [ -f "$ISO" ];
then
    abort "ERROR: Cannot access '$ISO'."
fi


WIN_D_CONTENTS=$(ls -A "$WIN_D")

if ! [ "$WIN_D_CONTENTS" == "" ];
then
    echo "There is a CD already loaded."
    echo "Ejecting it first..."

    wincd_eject

    if [ "$?" == "1" ];
    then
	    abort "Failed!"
    fi
fi


fuseiso "$ISO" "$WIN_D"


if ! [ "$?" == "0" ];
then
    echo "Failed loading ISO."
    abort "If trying to load a .CUE/BIN image, load the .BIN part, not .CUE."
fi


echo "ISO loaded at '$WIN_D'."
echo ""

