#!/bin/bash

DIR=$1

echo "Checking if can write in $DIR ..."

touch "$DIR/touched" &> /dev/null

if ! [ "$?" == "0" ];
then
    echo ""
    echo "Can't write in '$DIR'"
    echo "Have permission for using super-user privileges?"

    sudo touch "$DIR/touched" > /dev/null

    if ! [ "$?" == "0" ];
    then
        echo ""
        echo "It seems not. Sorry, you can't write there."
        exit 1
        
    else
        echo ""
        echo "Yes. You have them. Let's continue then."
        
        sudo rm "$DIR/touched"
        
        exit 2
    fi
fi

echo "You can write with your user."

rm "$DIR/touched"

exit 0
