#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function setup_prefix
{
    WINEPREFIX=$1
    WINEARCH=$2

    echo "Initializing prefix '$WINEPREFIX' with archtecture $WINEARCH..."
    wineboot

    if ! [ "$?" == "0" ];
    then
        echo "Initialization failed. Maybe a permissions problem."
        abort "Do chmod -R 770 in '$1' and try again."
    fi

    install_activator $WINEPREFIX $WINEARCH

    echo "Initialization done."
    echo ""
}


function usage
{
    echo "Usage: win_prepare <prefix name> [win32|win64]"
    echo ""
    echo "Setups a new Wine prefix."
    echo ""
    echo "All WINE prefixes goes in ~/.local/share/wineprefixes by default."
    echo "To use another location, set it in WIN_ROOT environment variable."
    echo "If no architecture is selected, win32 is used by default."
    echo ""
    echo "If an existing prefix is detected, and no activator is found there,"
    echo "one new will be created."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--h" ];
then
    usage
    exit 1
fi




PREFIX_NAME=$1


if ! [ "$WIN_ROOT" == "" ] && [ -d "$WIN_ROOT" ];
then
    export PREFIXES_ROOT=$WIN_ROOT

    touch "$PREFIXES_ROOT/touched"

    if ! [ "$?" == "0" ];
    then
        abort "ERROR: Cannot write in '$PREFIXES_ROOT'"
    else
        rm "$PREFIXES_ROOT/touched"
    fi
else
    export PREFIXES_ROOT=$HOME/.local/share/wineprefixes
fi

echo "Using '$PREFIXES_ROOT' as prefixes root."


if [ -d "$PREFIXES_ROOT/$PREFIX_NAME/dosdevices" ];
then
    abort "There is already a WINE prefix named '$PREFIX_NAME' here."
fi

