#!/bin/bash

if [ "$WIN_D" == "" ];
then
    echo "No WINE prefix loaded."
    echo "Call wine_load <prefix name> [win32|win64]"
    echo "Set WIN_ROOT if need to use a different path as prefixes root."
    echo ""
    exit 1
fi


dir_empty "$WIN_D"

if [ "$?" == "0" ];
then
    echo "No CD found in drive D."
    echo ""
    exit 1
fi

echo "Ejecting CD in drive D..."
fusermount -u "$WIN_D"

if ! [ "$?" == "0" ];
then
    echo "Failed unmounting ISO."
    echo ""
    exit 1
fi

echo "Done."
echo ""

