#!/bin/bash

function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}




if ! [ -f "/usr/bin/fusermount" ];
then
    echo "Installing fuseiso ..."
    echo "----------------------"

    sudo apt install -y fuseiso
fi

if ! [ "$?" == "0" ];
then
    abort "Failed."    
fi


if [ "$WIN_D" == "" ];
then
    echo "No WINE prefix loaded."
    echo "Call wine_load <prefix name> [win32|win64]"

    abort "Set WIN_ROOT if need to use a different path as prefixes root."
fi


WIN_D_CONTENTS=$(ls -A "$WIN_D")

if ! [ "$WIN_D_CONTENTS" == "" ];
then
    abort "No CD found in drive D."
fi


echo "Ejecting CD in drive D..."

fusermount -u "$WIN_D"

if ! [ "$?" == "0" ];
then
    abort "Failed unmounting ISO."
fi


echo "Done."
echo ""

