#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{

}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




EXEC=$1
FILE_TYPE=$(file -L "$EXEC")


echo ${FILE_TYPE} | grep "ELF 32-bit" > /dev/null

if [ "$?" == "0" ];
then
    LINUX_X86=1

    echo "linux-i386"
    echo ""
fi


echo ${FILE_TYPE} | grep "ELF 64-bit" > /dev/null

if [ "$?" == "0" ];
then
    LINUX_X64=1

    echo "linux-amd64"
    echo ""
fi


echo ${FILE_TYPE} | grep "PE32 executable" > /dev/null

if [ "$?" == "0" ];
then
    WINDOWS_X86=1

    echo "windows-i386"
    echo ""
fi


echo ${FILE_TYPE} | grep "PE32+ executable" > /dev/null

if [ "$?" == "0" ];
then
    WINDOWS_X64=1

    echo "windows-amd64"
    echo ""
fi

