#!/bin/bash


function usage
{
    echo "Usage: use_wine <Wine path>"
    echo ""
    echo "Activates one Wine installation for use."
    echo ""
    echo "Basically, sets some environment variables and aliases:"
    echo ""
    echo "Environment variables:"
    echo "======================"
    echo "- WINE_PATH: Points to the Wine installation in use."
    echo ""
    echo "- BOX{ARCH}_LD_LIBRARY_PATH: Points where Wine Linux libs reside."
    echo "                             'lib{ARCH}/wine/{ARCH}-unix'"
    echo ""
    echo "- WINEDLLPATH: Points to the 'lib{ARCH}/wine/{ARCH}-windows'"
    echo "               folder where the Windows DLLs Wine needs reside."
    echo ""
    echo "- WINELOADER: Points to the Wine executable."
    echo "- WINESERVER: Points to the wineserver executable."
    echo "- WINEDEBUG: Disables the 'fixme' messages."
    echo ""
    echo "Aliases:"
    echo "========"
    echo "- wine, winecfg, wineboot, winefile."
    echo ""
    echo "The environment variables related to Box86/64 are only set if"
    echo "box86/64 are found in PATH."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage

else
    if ! [ "$TERMUX_VERSION" == "" ];
    then
        echo "This script isn't for Termux."
        echo ""

    else
        export WINE_PATH=$1


        if ! [ -f "${WINE_PATH}/.wine_branch" ];
        then
            echo "No Wine installation found at '$WINE_PATH'."
            echo ""

        else
            WINE_ARCH=$(cat "$WINE_PATH/.wine_arch")
            WINE_BRANCH=$(cat "$WINE_PATH/.wine_branch")
            WINE_VERSION=$(cat "$WINE_PATH/.wine_version")

            WINE_BINARIES="${WINE_PATH}/opt/wine-${WINE_BRANCH}/bin"

            WINE_UTILS="${WINE_PATH}/opt/wine-${WINE_BRANCH}"
            
            if [ "$WINE_ARCH" == "i386" ];
            then
                WINE_UTILS+="/lib/wine/i386-windows"
            else
                WINE_UTILS+="/lib64/wine/x86_64-windows"
            fi

            if [ -f "${WINE_BINARIES}/wine64" ];
            then
                export WINEARCH=win64

                export WINELOADER="${WINE_BINARIES}/wine64"
                
                export WINEDLLPATH="${WINE_PATH}/opt/wine-${WINE_BRANCH}"
                export WINEDLLPATH+="/lib64/x86_64-windows"

                if [ -f "/usr/local/bin/box64" ];
                then
                    WINE_SO_PATH="${WINE_PATH}/opt/wine-${WINE_BRANCH}"
                    WINE_SO_PATH+="/lib64/x86_64-unix"

                    echo "$WINE_SO_PATH" | grep -q "$BOX64_LD_LIBRARY_PATH"

                    if ! [ "$?" == "0" ];
                    then
                        export $BOX64_LD_LIBRARY_PATH+=":$WINE_SO_PATH"
                    fi
                fi

            else
                export WINEARCH=win32
                
                export WINELOADER="${WINE_BINARIES}/wine"
                
                export WINEDLLPATH="${WINE_PATH}/opt/wine-${WINE_BRANCH}"
                export WINEDLLPATH+="/lib/i386-windows"

                if [ -f "/usr/local/bin/box86" ];
                then
                    WINE_SO_PATH="${WINE_PATH}/opt/wine-${WINE_BRANCH}"
                    WINE_SO_PATH+="/lib/i386-unix"

                    echo "$WINE_SO_PATH" | grep -q "$BOX86_LD_LIBRARY_PATH"

                    if ! [ "$?" == "0" ];
                    then
                        export $BOX86_LD_LIBRARY_PATH+=":$WINE_SO_PATH"
                    fi
                fi
            fi

            export WINESERVER="${WINE_BINARIES}/wineserver"
            export WINEDEBUG=-all

            alias wine="${WINELOADER}"
            alias wineboot="wine ${WINE_UTILS}/wineboot.exe"
            alias winecfg="wine ${WINE_UTILS}/winecfg.exe"
            alias winefile="wine ${WINE_UTILS}/winefile.exe"


            echo -n "Using Wine (${WINEARCH}) ${WINE_BRANCH} (${WINE_VERSION}) "
            echo "installation at '${WINE_PATH}'."
            echo ""
        fi
    fi
fi


