#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: use_wine <Wine path>"
    echo ""
    echo "Activates one Wine installation for use."
    echo ""
    echo "Basically, sets some environment variables and aliases:"
    echo "- WINE_PATH: Points to the Wine installation in use."
    echo "- WINELOADER: Points to the Wine executable."
    echo "- WINESERVER: Points to the wineserver executable."
    echo "- WINEDEBUG: Disables the 'fixme' messages."
    echo ""
    echo "- wine, winecfg, wineboot: Aliases for these commands."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




if ! [ "$TERMUX_VERSION" == "" ];
then
    abort "This script isn't for Termux."
fi


export WINE_PATH=$1


if ! [ -f "${WINE_PATH}/.wine_branch" ];
then
    abort "Wine not detected '$WINE_PATH'."
fi


WINE_BRANCH=$(cat "$WINE_PATH/.wine_branch")
WINE_VERSION=$(cat "$WINE_PATH/.wine_version")

WINE_BINARIES="${WINE_PATH}/opt/wine-${WINE_BRANCH}/bin"


if [ -f "${WINEBINARIES}/wine64" ];
then
    export WINELOADER="${WINE_BINARIES}/wine64"
    export WINEARCH=win64
else
    export WINELOADER="${WINE_BINARIES}/wine"
    export WINEARCH=win32
fi

export WINESERVER="${WINEBINARIES}/wineserver"
export WINEDEBUG=-all

alias wine='${WINELOADER}'
alias winecfg='${WINEBINARIES}/winecfg'
alias wineboot='${WINEBINARIES}/wineboot'

echo "Using Wine (${WINEARCH}) ${WINE_BRANCH} (${WINE_VERSION}) \ 
      installation at '${WINE_PATH}'."

echo ""


