#!/bin/bash


function usage
{
    echo "Usage: use_wine <Wine path>"
    echo ""
    echo "Activates one Wine installation for use."
    echo ""
    echo "Basically, sets some environment variables and aliases:"
    echo ""
    echo "Environment variables:"
    echo "======================"
    echo "- WINE_PATH: Points to the Wine installation in use."
    echo "- WINELOADER: Points to the Wine executable."
    echo "- WINESERVER: Points to the wineserver executable."
    echo "- WINEDEBUG: Disables the 'fixme' messages."
    echo ""
    echo "Aliases:"
    echo "========"
    echo "- wine, winecfg, wineboot, winefile."
    echo ""
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage

else
    if ! [ "$TERMUX_VERSION" == "" ];
    then
        echo "This script isn't for Termux."
        echo ""

    else
        export WINE_PATH=$1


        if ! [ -f "${WINE_PATH}/.wine_branch" ];
        then
            echo "No Wine installation found at '$WINE_PATH'."
            echo ""

        else
            WINE_ARCH=$(cat "$WINE_PATH/.wine_arch")
            WINE_BRANCH=$(cat "$WINE_PATH/.wine_branch")
            WINE_VERSION=$(cat "$WINE_PATH/.wine_version")

            WINE_BINARIES="${WINE_PATH}/opt/wine-${WINE_BRANCH}/bin"

            WINE_UTILS="${WINE_PATH}/opt/wine-${WINE_BRANCH}"
            
            if [ "$WINE_ARCH" == "i386" ];
            then
                WINE_UTILS+="/lib/wine/i386-windows"
            else
                WINE_UTILS+="/lib64/wine/x86_64-windows"
            fi

            if [ -f "${WINE_BINARIES}/wine64" ];
            then
                export WINELOADER="${WINE_BINARIES}/wine64"
                export WINEARCH=win64
            else
                export WINELOADER="${WINE_BINARIES}/wine"
                export WINEARCH=win32
            fi

            export WINESERVER="${WINE_BINARIES}/wineserver"
            export WINEDEBUG=-all

            alias wine="${WINELOADER}"            
            alias wineboot="wine ${WINE_UTILS}/wineboot.exe"
            alias winecfg="wine ${WINE_UTILS}/winecfg.exe"
            alias winefile="wine ${WINE_UTILS}/winefile.exe"


            echo -n "Using Wine (${WINEARCH}) ${WINE_BRANCH} (${WINE_VERSION}) "
            echo "installation at '${WINE_PATH}'."
            echo ""
        fi
    fi
fi


