#!/bin/bash

function abort
{
    REASON=$1

    if [ "$REASON" == "" ];
    then
        echo $REASON
    fi

    echo ""
    
    exit 1
}


function usage
{
    echo "Usage: win_start <windows executable path>"
    echo "Activates the needed Wine prefix and runs the executable."
    echo ""
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi


SCRIPT_DIR=$(realpath $(dirname $0))




EXEC=$1
EXEC_NAME=$(basename $EXEC)
EXEC_PATH=$(dirname $EXEC)

ARGS=${@:2}


if [ "$EXEC_PATH/${EXEC_NAME}_winenv" ];
then
    source "$EXEC_PATH/${EXEC_NAME}_winenv"
else
    EXEC_TYPE=$("$SCRIPT_DIR/exec_type" "$EXEC")

    if [ "$EXEC_TYPE" == "windows-i386" ];
    then
        EXEC_BITS=32

    elif [ "$EXEC_TYPE" == "windows-amd64" ];
    then
        EXEC_BITS=64
    fi


    if [ "$EXEC_BITS" == "32" ];
    then
        if [ "$HOME/.default_win32_env" ];
        then
            source "$HOME/.default_win32_env"
        fi
    else
        if [ "$HOME/.default_win64_env" ];
        then
            source "$HOME/.default_win64_env"
        fi
    fi
fi


echo "Windows ${EXEC_BITS} binary detected."
echo "Executing '$EXEC' $ARGS with Wine ..."
echo ""

